# Generated by Django 5.0.6 on 2024-08-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=200, verbose_name='نام کامل')),
                ('Phone', models.CharField(max_length=50, null=True, verbose_name='شماره تماس')),
                ('Email', models.EmailField(max_length=200, verbose_name='ایمیل')),
            ],
        ),
    ]
