# Generated by Django 5.0.6 on 2024-08-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
