# Generated by Django 5.0.6 on 2024-08-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$MaexEuiy1r0BYY486Ml3PR$mxEMOsXsiqHFZzJ70lcws53EBw5dDXXKhT5zwnjLfYE=', max_length=128, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='ایمیل'),
        ),
    ]
