# Generated by Django 5.1.1 on 2024-09-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='categories/default-category.jpg', null=True, upload_to='categories/'),
        ),
    ]
