# Generated by Django 5.1.1 on 2024-09-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MostSoldProduct',
        ),
    ]
